var CLIENT_MSG;
(function (CLIENT_MSG) {
    CLIENT_MSG[CLIENT_MSG["CM_LOGIN"] = 1] = "CM_LOGIN";
    CLIENT_MSG[CLIENT_MSG["CM_CREATE_ROOM"] = 2] = "CM_CREATE_ROOM";
    CLIENT_MSG[CLIENT_MSG["CM_ENTER_ROOM"] = 3] = "CM_ENTER_ROOM";
    CLIENT_MSG[CLIENT_MSG["CM_LEAVE_ROOM"] = 4] = "CM_LEAVE_ROOM";
    CLIENT_MSG[CLIENT_MSG["CM_READY_GAME"] = 5] = "CM_READY_GAME";
    CLIENT_MSG[CLIENT_MSG["CM_START_GAME"] = 6] = "CM_START_GAME";
    CLIENT_MSG[CLIENT_MSG["CM_GET_ROOM_INFO"] = 7] = "CM_GET_ROOM_INFO";
    CLIENT_MSG[CLIENT_MSG["CM_CHU_PAI"] = 8] = "CM_CHU_PAI";
    CLIENT_MSG[CLIENT_MSG["CM_RESPON_CHU_PAI"] = 9] = "CM_RESPON_CHU_PAI";
    CLIENT_MSG[CLIENT_MSG["CM_HUAN_PAI"] = 10] = "CM_HUAN_PAI";
})(CLIENT_MSG || (CLIENT_MSG = {}));
var SERVER_MSG;
(function (SERVER_MSG) {
    SERVER_MSG[SERVER_MSG["SM_LOGIN"] = 1] = "SM_LOGIN";
    SERVER_MSG[SERVER_MSG["SM_CREATE_ROOM"] = 2] = "SM_CREATE_ROOM";
    SERVER_MSG[SERVER_MSG["SM_ENTER_ROOM"] = 3] = "SM_ENTER_ROOM";
    SERVER_MSG[SERVER_MSG["SM_LEAVE_ROOM"] = 4] = "SM_LEAVE_ROOM";
    SERVER_MSG[SERVER_MSG["SM_READY_GAME"] = 5] = "SM_READY_GAME";
    SERVER_MSG[SERVER_MSG["SM_START_GAME"] = 6] = "SM_START_GAME";
    SERVER_MSG[SERVER_MSG["SM_MO_PAI"] = 7] = "SM_MO_PAI";
    SERVER_MSG[SERVER_MSG["SM_CHU_PAI"] = 8] = "SM_CHU_PAI";
    SERVER_MSG[SERVER_MSG["SM_HUAN_PAI"] = 9] = "SM_HUAN_PAI";
    SERVER_MSG[SERVER_MSG["SM_PENG_PAI"] = 10] = "SM_PENG_PAI";
    SERVER_MSG[SERVER_MSG["SM_GANG_PAI"] = 11] = "SM_GANG_PAI";
    SERVER_MSG[SERVER_MSG["SM_HU_PAI"] = 12] = "SM_HU_PAI";
    SERVER_MSG[SERVER_MSG["SM_GAME_BALANCE"] = 13] = "SM_GAME_BALANCE";
})(SERVER_MSG || (SERVER_MSG = {}));
function CreateMsg(id, msg) {
    return JSON.stringify([id, msg]);
}
